name: Flutter CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout source code
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4

      # Setup Java 17
      - name: ☕ Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Setup Flutter
      - name: 🐦 Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.1'

      # Cek versi Flutter & Dart
      - name: 🔍 Check Version
        run: |
          flutter --version
          dart --version

      # Flutter Doctor
      - name: 🩺 Flutter Doctor
        run: flutter doctor -v

      # Bersihkan cache Flutter & Gradle
      - name: 🧹 Clean Project
        run: |
          flutter clean
          rm -rf ~/.gradle/caches

      # Install dependency
      - name: 📦 Install Dependencies
        run: flutter pub get

      # Test (opsional)
      - name: 🧪 Run Tests
        run: flutter test
        continue-on-error: true

      # Build APK
      - name: 🏗️ Build APK
        run: flutter build apk --release --verbose

      # Upload APK
      - name: 📤 Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk


      - name: 📢 Notify Telegram (Success)
        if: success()
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d text="✅ Build APK berhasil untuk commit ${{ github.sha }}"
          
          

      - name: ❌ Notify Telegram (Failed)
        if: failure()
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d text="❌ Build gagal di workflow GitHub Actions"

      - name: 📤 Send APK to Telegram
        if: success()
        run: |
          curl -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendDocument \
          -F chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -F document=@build/app/outputs/flutter-apk/app-release.apk \
          -F caption="📦 APK terbaru berhasil di-build 🚀"